line-length = 120
target-version = "py310"

exclude = ["venv", "__pycache__", "alembic/versions"]

select = ["E", "F", "W", "I", "N", "D", "UP", "PL", "A", "B", "RUF"]

ignore = ["E501", "D100", "D104", "D107", "D203", "D213", "D401", "D413", "PLR0913", "PLR0915", "PLW2901"]

[pydocstyle]
convention = "google"