[tool.black]
line-length = 120
target-version = ['py310']

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_context = true
pretty = true

strict_optional = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

exclude = ['venv', 'alembic/versions']